name: Deploy

on:
  push:
    branches:
      - master

jobs:
  Build:
    name: Build And Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC}}'

      - run: cp .env.production .env
      - run: yarn
      - run: yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: public
